name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'github-pages'
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.environment || 'github-pages' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' 
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Node.js Dependencies
        run: npm ci
      - name: Install Python Dependencies
        run: pip install -r requirements.txt 
      - name: Generate Index Content
        run: python generate_index.py 
      - name: Build Quartz
        env:
            POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
            POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
