name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    env:
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Check if POSTHOG_API_KEY is set
        run: |
          if [ -z "${POSTHOG_API_KEY}" ]; then
            echo "❌ POSTHOG_API_KEY is not set! PostHog will be disabled or the build might fail."
            # Uncomment the next line if you want to FAIL the workflow when missing:
            # exit 1
          else
            echo "✅ POSTHOG_API_KEY is set."
          fi
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4